<Project Sdk="Microsoft.NET.Sdk.Web">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <RootNamespace>EcommercePlugin</RootNamespace>
    <AssemblyName>EcommercePlugin</AssemblyName>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="ECommerce.IntegrationContracts" Version="1.0.0" />
    <PackageReference Include="ECommerce.PluginContracts" Version="1.0.0" />
  </ItemGroup>
</Project>
